runtime: nodejs14

instance_class: F1

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always

# includes:
#   - secret.yaml

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: "production"
  ESTAT_APPID: '724e5b90772a3e9289f41a253e4e7e32438f4fff'
  RESAS_API_KEY: '02JYzLqUOfTNVfiTWjLlR2g0YwEQPQ7caYxcnZaZ'
  SITE_URL: '02JYzLqUOfTNVfiTWjLlR2g0YwEQPQ7caYxcnZaZ'