steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cat << EOF > secret.yaml
        env_variables:
          ESTAT_APPID: $_ESTAT_APPID
          RESAS_API_KEY: $_RESAS_API_KEY
        EOF
  - name: node:14
    entrypoint: yarn
    args:
      - 'install'
  - name: node:14
    entrypoint: yarn
    args:
      - 'build'
    env:
      - 'ESTAT_APPID=$_ESTAT_APPID'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - app
      - deploy
      - '--appyaml=${_APP_YAML}'
      - '--project=${PROJECT_ID}'
      - '--version=${_VERSION}'
      - '--quiet'
timeout: 1200s
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _APP_YAML: 'app.yaml'
  _VERSION: '${COMMIT_SHA}'