steps:
  - name: node:14
    entrypoint: yarn
    args:
      - 'install'
  - name: node:14
    entrypoint: yarn
    args:
      - 'build'
    env:
      - 'ESTAT_APPID=$_ESTAT_APPID'
      - 'SITE_URL=$_SITE_URL'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - app
      - deploy
      - '--appyaml=${_APP_YAML}'
      - '--project=${PROJECT_ID}'
      - '--version=${_VERSION}'
      - '--quiet'
timeout: 1200s
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _APP_YAML: 'app.yaml'
  _VERSION: '${COMMIT_SHA}'