steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        cat << EOF > secret.yaml
        env_variables:
          SITE_URL: $_SITE_URL
          ESTAT_APPID: $_ESTAT_APPID
          RESAS_API_KEY: $_RESAS_API_KEY
        EOF
  - name: node:14
    entrypoint: yarn
    args:
      - 'install'
  - name: node:14
    entrypoint: yarn
    args:
      - 'build'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - app
      - deploy
      - '--appyaml=${_APP_YAML}'
      - '--project=${PROJECT_ID}'
      - '--version=${_VERSION}'
      - '--quiet'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - seleniumSample
      - --region=asia-northeast2
      - --runtime=python39
      - --source=functions/ogp-selenium/
      - --trigger-http
      - --allow-unauthenticated
      - --entry-point seleniumSample
      - --memory 1GB
timeout: 1200s
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _APP_YAML: 'app.yaml'
  _VERSION: '${COMMIT_SHA}'