// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Entry } from 'contentful'
// import { Document } from '@contentful/rich-text-types'

export interface IGovernmentTypeFields {
  /** governmentId */
  governmentId?: string | undefined

  /** governmentTitle */
  governmentTitle?: string | undefined
}

export interface IGovernmentType extends Entry<IGovernmentTypeFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'governmentType'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IStatisticsFieldFields {
  /** fieldId */
  fieldId: string

  /** fieldTitle */
  fieldTitle: string
}

/** 統計分野 */

export interface IStatisticsField extends Entry<IStatisticsFieldFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'statisticsField'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IStatisticsMenuFields {
  /** menuId */
  menuId: string

  /** menuTitle */
  menuTitle: string

  /** fieldId */
  fieldId:
    | 'landweather'
    | 'population'
    | 'laborwage'
    | 'agriculture'
    | 'miningindustry'
    | 'commercial'
    | 'economy'
    | 'construction'
    | 'energy'
    | 'tourism'
    | 'educationsports'
    | 'administrativefinancial'
    | 'safetyenvironment'
    | 'socialsecurity'
    | 'international'

  /** govType */
  govType: ('prefecture' | 'city')[]

  /** initialMenu */
  initialMenu: boolean
}

/** 統計項目 */

export interface IStatisticsMenu extends Entry<IStatisticsMenuFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'statisticsMenu'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE =
  | 'governmentType'
  | 'statisticsField'
  | 'statisticsMenu'

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
